#.travis.yml

dist: xenial

language: node_js
node_js:
  - "11"

before_script:
  - sudo apt install build-essential
  - sudo snap install --classic snapcraft
#  - cd frontend/web/
#  - npm install

script:
  - snapcraft snap -o ./strangescout.snap
#  - ./node_modules/.bin/ng build --prod --aot --source-map=false
#  - cd ../..

deploy:
  provider: snap
  snap: strangescout.snap
  channel: edge
  skip_cleanup: true
  on:
    branch: snapcraft

notifications:
  email:
    on_failure: change
    on_success: change
