#.travis.yml

dist: xenial

language: node_js
node_js:
  - "11"

before_script:
  - sudo apt install build-essential
  - sudo snap install --classic snapcraft

script:
  - make build
  - make snap

deploy:
  provider: snap
  snap: strangescout.snap
  channel: edge
  skip_cleanup: true
  on:
    branch: snapcraft

notifications:
  email:
    on_failure: change
    on_success: change
