#.travis.yml

dist: xenial

language: node_js
node_js:
  - "11"
services:
  - docker

before_script:
  - sudo apt install build-essential
#  - sudo snap install --classic snapcraft

script:
  - make
  - make docker
#  - make snap

deploy:
  - provider: script
    script: bash docker/deploy.sh
    skip_cleanup: true
    on:
      repo: triplestrange/StrangeScout
      all_branches: true
      condition: ( "$TRAVIS_BRANCH" == "master" ) || ( -n "$TRAVIS_TAG" )
#  - provider: snap
#    snap: strangescout.snap
#    channel: edge
#    skip_cleanup: true
#    on:
#      repo: triplestrange/StrangeScout
#      all_branches: true
#      condition: ( "$TRAVIS_BRANCH" == "master" ) || ( -n "$TRAVIS_TAG" )

notifications:
  email:
    on_failure: change
    on_success: change
