version: '3.5'
services:
        jscout:
                build: jscout/
                  dockerfile: Dockerfile_traefik
                restart: always
                depends_on:
                        - "goscout"
                environment:
                        JSCOUT_DOMAIN:
                        GOSCOUT_HOST: "goscout"
                expose: # this container exports HTTP-as-a-service
                        - "80"
                networks:
                        - "traefik"
                        - "default"
                labels:
                        traefik.enable: "true"
                        traefik.docker.network: "${TRAEFIK_NETWORK}"
                        traefik.port: "80"
                        traefik.frontend.rule: "Host:$JSCOUT_DOMAIN,www.$JSCOUT_DOMAIN"
                        traefik.frontend.headers.STSSeconds: "31536000"
                        traefik.frontend.headers.STSIncludeSubdomains: "true"
                        traefik.frontend.headers.STSPreload: "true"

        goscout:
                build: goscout/
                restart: always
                depends_on:
                        - "strangedb"
                environment:
                        GOSCOUT_SQL_USER: "strangescout"
                        GOSCOUT_SQL_PASSWD: "${STRANGESCOUT_SQL_PASSWD}"
                        GOSCOUT_SQL_HOST: "strangedb"
                        GOSCOUT_EVENT_HARDCODE:
                expose: # for internal use, proxied by jscout container
                        - "15338"

                labels:
                        traefik.enable: "false"
        
        strangedb:
                image: mariadb
                restart: always
                volumes:
                        - type: volume
                          source: strangedb
                          target: /var/lib/mysql
                environment:
                        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
                        MYSQL_DATABASE: "strangescout"
                        MYSQL_PASSWORD: "${STRANGESCOUT_SQL_PASSWD}"
                        MYSQL_USER: "strangescout" 
                expose:
                        - "3306"
                ports: # should probably not leave this open in production
                        - "3306:${MYSQL_PUBLIC_PORT}"

                labels:
                        traefik.enable: "false"

volumes:
        strangedb:
             name: ${PREFIX}_strangedb
networks:
        traefik:
                external: true
                name: ${TRAEFIK_NETWORK}
