version: "3.4"
services:
        jscout:
                build: jscout/
                restart: always
                depends_on:
                        - "goscout"
                environment:
                        JSCOUT_DOMAIN:
                        GOSCOUT_HOST: "goscout"
                expose: # this container exports HTTP-as-a-service
                        - "80"
        goscout:
                build: goscout/
                restart: always
                depends_on:
                        - "strangedb"
                environment:
                        GOSCOUT_SQL_USER: "strangescout"
                        GOSCOUT_SQL_PASSWD: "${STRANGESCOUT_SQL_PASSWD}"
                        GOSCOUT_SQL_HOST: "strangedb"
                        GOSCOUT_EVENT_HARDCODE:
                expose: # for internal use, proxied by jscout container
                        - "15338"
        
        strangedb:
                image: mariadb
                restart: always
                volumes:
                        - type: volume
                          source: strangedb
                          target: /var/lib/mysql
                environment:
                        MYSQL_RANDOM_ROOT_PASSWORD: "yes"
                        MYSQL_DATABASE: "strangescout"
                        MYSQL_PASSWORD: "${STRANGESCOUT_SQL_PASSWD}"
                        MYSQL_USER: "strangescout" 
                expose:
                        - "3306"
                ports: # should probably not leave this open in production
                        - "3306:${MYSQL_PUBLIC_PORT}"

volumes:
        strangedb:
             name: "${PREFIX}_strangedb"
networks:
        ${TRAEFIK_NETWORK}:
                external: true
