version: "3.5"
services:
        jscout:
                build: jscout/
                restart: always
                depends_on:
                        - "strangedb"
                volumes:
                        - type: volume
                          source: jscout_caddydir
                          target: /.caddy
                          volume:
                                 nocopy: true
                environment:
                        JSCOUT_DOMAIN: ${JSCOUT_DOMAIN?did not set the domain name}
                        JSCOUT_LETS_ENCRYPT_EMAIL: ${JSCOUT_LETS_ENCRYPT_EMAIL?did not set the Lets Encrylt email}
                        COUCHDB_HOST: "strangedb"
                ports:
                        - "80:80"
                        - "443:443"
        strangedb:
                image: treehouses/couchdb:2.2.0
                restart: always
                volumes:
                        - type: volume
                          source: strangedb
                          target: /opt/couchdb
                        - type: volume
                          source: strangedb_data
                          target: /opt/couchdb/data
                environment:
                        COUCHDB_PASSWORD: "${STRANGESCOUT_DB_PASSWD?did not set password!}"
                        COUCHDB_USER: "strangescout"
                expose:
                        - "5984"
                ports:
                        - "{$COUCHDB_PUBLIC_PORT:-5984}:5984"

volumes:
        strangedb:
                name: {$PREFIX-prod}_strangedb
        strangedb_data:
                name: ${PREFIX-prod}_strangedb_data
        jscout_caddydir: # stores certs--if you don't persist these you will QUICKLY hit a Let's Encrypt ratelimit!
                name: ${PREFIX-prod}_jscout_caddydir
