version: '3.5'
services:
        jscout:
                build:
                        context: ./jscout/
                        dockerfile: Dockerfile-traefik
                restart: always
                depends_on:
                        - "goscout"
                environment:
                        JSCOUT_DOMAIN: ${JSCOUT_DOMAIN?did not set the domain name}
                        GOSCOUT_HOST: "goscout"
                expose: # this container exports HTTP-as-a-service
                        - "80"
                networks:
                        - "traefik"
                        - "default"
                labels:
                        traefik.enable: "true"
                        traefik.docker.network: "${TRAEFIK_NETWORK?did not setup network to reach traefik on}"
                        traefik.port: "80"
                        traefik.frontend.rule: "Host:${JSCOUT_DOMAIN?did not set domain},www.$JSCOUT_DOMAIN"
                        traefik.frontend.headers.STSSeconds: "31536000"
                        traefik.frontend.headers.STSIncludeSubdomains: "true"
                        traefik.frontend.headers.STSPreload: "true"

        strangedb:
                image: couchdb
                restart: always
                volumes:
                        - type: volume
                          source: strangedb
                          target: /opt/couchdb
                environment:
                        COUCHDB_PASSWORD: "${STRANGESCOUT_DB_PASSWD?did not set password!}"
                        COUCHDB_USER: "strangescout"
                expose:
                        - "5984"
                ports:
                        - "{$COUCHDB_PUBLIC_PORT:-5984}:5984"
                labels:
                        traefik.enable: "false"

volumes:
        strangedb:
                name: ${PREFIX-prod}_strangedb
networks:
        traefik:
                external: true
                name: ${TRAEFIK_NETWORK?did not set a network to reach traefik on}
